### ISSUE TITLE
FYI: Extension 0.3.0 doesn't launch on QuPath 0.5.0RC1

### ISSUE THREAD

**Issue by psobolewskiPhD** [qupath/qupath-extension-omero-web#27]
Just an FYI that this extension isn't launching with QuPath 0.5.0RC1
My log shows:
```
09:28:22.180	[JavaFX Application Thread]	WARN	qupath.lib.gui.ExtensionManager	QuPath version for which the 'OMERO extension' was written is unknown!
```
and
```
09:28:22.174	[JavaFX Application Thread]	ERROR	qupath.lib.gui.ExtensionManager	Error loading extension qupath.lib.images.servers.omero.OmeroExtension@786a2205: qupath/lib/gui/ActionTools	java.lang.NoClassDefFoundError: qupath/lib/gui/ActionTools
	at qupath.lib.images.servers.omero.OmeroExtension.installExtension(OmeroExtension.java:73)
	at qupath.lib.gui.ExtensionManager.refreshExtensions(ExtensionManager.java:148)
	at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:343)
	at qupath.lib.gui.QuPathGUI.createInstance(QuPathGUI.java:410)
	at qupath.lib.gui.QuPathApp.start(QuPathApp.java:65)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.ClassNotFoundException: qupath.lib.gui.ActionTools
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more

```

**Comment by psobolewskiPhD** [comment]
Irrelevant now.
